# Imports and Load

In [3]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_halving_search_cv
enable_halving_search_cv
from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV
import xgboost as xgb
import mlflow
import re

mlflow.set_tracking_uri("http://localhost:5000")
print("Tracking URI:", mlflow.get_tracking_uri())

mlflow.set_experiment("customer-churn")
from mlflow.tracking import MlflowClient
client = MlflowClient()

Tracking URI: http://localhost:5000

In [4]:
with open('./data/train.csv', 'r') as f:
    df = pd.read_csv(f)

In [5]:
df.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [6]:
numeric_cols = []
categorical_cols = []

for col in df.columns:
    if df[col].dtype in ['object', 'str'] or df[col].nunique() == 2:
        categorical_cols.append(col)
    elif df[col].dtype in ['int64', 'float64']:
        if df[col].nunique() < 6:
            categorical_cols.append(col)
        else:
            numeric_cols.append(col)

print(f"Numeric Columns: {numeric_cols}")
print(f"Categorical Columns: {categorical_cols}")

Numeric Columns: ['id', 'tenure', 'MonthlyCharges', 'TotalCharges']
Categorical Columns: ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']

---
# 3. Dataset split

In [7]:
df_copy = df.copy()
df_copy = df_copy.drop("id", axis=1)
numeric_cols_ = numeric_cols.copy()
numeric_cols_.remove("id")
categorical_cols_ = categorical_cols.copy()
categorical_cols_.remove("Churn")
X = df_copy.drop("Churn", axis=1)
X = pd.concat([
    X.select_dtypes([], ['object']),
    X.select_dtypes(['object']).apply(pd.Series.astype, dtype='category')
    ], axis=1)


y = df_copy["Churn"].map({"No": 0, "Yes": 1})

X_train, X_val, y_train, y_val = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)

# 4. Feature engineering

In [8]:
X_train.dtypes

SeniorCitizen          int64
tenure                 int64
MonthlyCharges       float64
TotalCharges         float64
gender              category
Partner             category
Dependents          category
PhoneService        category
MultipleLines       category
InternetService     category
OnlineSecurity      category
OnlineBackup        category
DeviceProtection    category
TechSupport         category
StreamingTV         category
StreamingMovies     category
Contract            category
PaperlessBilling    category
PaymentMethod       category
dtype: object

In [9]:
X_train.iloc[[0]]

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
512656,1,13,91.0,1222.65,Male,No,No,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,No,Month-to-month,Yes,Electronic check

# 5. Modeling

## XGBoost with RandomSearchCV

In [12]:
with mlflow.start_run(run_name="random_search_trial") as run:
    mlflow.set_tag("tuning_type", "random-search")
    run_id = run.info.run_id

    model = xgb.XGBClassifier(
        objective='binary:logistic',
        eval_metric='auc',
        enable_categorical=True,
        scale_pos_weight = 460000 / 133000,
        n_jobs=1
    )

    param_grid = {
        'n_estimators': [200, 400, 600, 800, 100],
        'max_depth': [2, 4, 8, 16, 32],
        'learning_rate': [0.01, 0.1, 0.3],
        'booster': ['gbtree'],
        'subsample': [0.8, 1],
        'colsample_bytree': [0.8, 1],
        'min_child_weight': [1, 3, 5, 7],
        'gamma': [0, 0.1, 0.3, 1],
        'reg_alpha': [0, 0.1, 1, 10],
        'reg_lambda': [0, 0.5, 1, 5, 10],

    }

    cv = StratifiedKFold(
        n_splits=3,
        shuffle=True,
        random_state=42
    )

    search = RandomizedSearchCV(
        estimator=model,
        param_distributions=param_grid,
        n_iter=10,
        scoring="roc_auc",
        cv=cv,
        verbose=3,
        n_jobs=-1
    )

    search.fit(X_train, y_train)

    print("Best params:")
    print(search.best_params_)

    print("Best mean AUC:")
    print(search.best_score_)
    
    mlflow.log_param("n_estimators", search.best_params_['n_estimators'])
    mlflow.log_param("max_depth", search.best_params_['max_depth'])
    mlflow.log_param("learning_rate", search.best_params_['learning_rate'])
    mlflow.log_param("booster", search.best_params_['booster'])
    mlflow.log_param("subsample", search.best_params_['subsample'])
    mlflow.log_param("colsample_bytree", search.best_params_['colsample_bytree'])
    mlflow.log_metric("roc_auc", search.score(X_val, y_val))
    mlflow.sklearn.log_model(search.best_estimator_, name='grid_xgb_model', input_example=X_train.iloc[[0]], registered_model_name="customer-churn",)

versions = client.search_model_versions(
    f"name='customer-churn' and run_id='{run_id}'"
)
version = versions[0].version

client.set_registered_model_alias(
    name="customer-churn",
    alias="candidate",
    version=version
)

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best params:
{'subsample': 0.8, 'reg_lambda': 5, 'reg_alpha': 1, 'n_estimators': 600, 'min_child_weight': 7, 'max_depth': 2, 'learning_rate': 0.3, 'gamma': 1, 'colsample_bytree': 1, 'booster': 'gbtree'}
Best mean AUC:
0.9153265643030087

2026/03/27 11:33:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
d:\Documents\ds-ml-portfolio\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/03/27 11:33:59 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: MlflowException("Failed to enforce schema of data '        SeniorCitizen  tenure  MonthlyCharges  TotalCharges gender Partner  \\\n512656              1      13            91.0       1222.65   Male      No   \n\n       Dependents PhoneService MultipleLines InternetService OnlineSecurity  \\\n512656         No          Yes           Yes     Fiber optic             No   \n\n       OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  \\\n512656           No              Yes          No         Yes              No   \n\n              Contract PaperlessBilling     PaymentMethod  \n512656  Month-to-month              Yes  Electronic check  ' with schema '['SeniorCitizen': long (required), 'tenure': long (required), 'MonthlyCharges': double (required), 'TotalCharges': double (required), 'gender': string (required), 'Partner': string (required), 'Dependents': string (required), 'PhoneService': string (required), 'MultipleLines': string (required), 'InternetService': string (required), 'OnlineSecurity': string (required), 'OnlineBackup': string (required), 'DeviceProtection': string (required), 'TechSupport': string (required), 'StreamingTV': string (required), 'StreamingMovies': string (required), 'Contract': string (required), 'PaperlessBilling': string (required), 'PaymentMethod': string (required)]'. Error: Incompatible input types for column gender. Can not safely convert category to <U0."). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`.
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2764.09it/s]
2026/03/27 11:34:02 WARNING mlflow.models.model: Failed to validate serving input example {
  "dataframe_split": {
    "columns": [
      "S.... Alternatively, you can avoid passing input example and pass model signature instead when logging the model. To ensure the input example is valid prior to serving, please try calling `mlflow.models.validate_serving_input` on the model uri and serving input example. A serving input example can be generated from model input example using `mlflow.models.convert_input_example_to_serving_input` function.
Got error: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:gender: object, Partner: object, Dependents: object, PhoneService: object, MultipleLines: object, InternetService: object, OnlineSecurity: object, OnlineBackup: object, DeviceProtection: object, TechSupport: object, StreamingTV: object, StreamingMovies: object, Contract: object, PaperlessBilling: object, PaymentMethod: object
Registered model 'customer-churn' already exists. Creating a new version of this model...
2026/03/27 11:34:03 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: customer-churn, version 3
Created version '3' of model 'customer-churn'.

🏃 View run random_search_trial at: http://localhost:5000/#/experiments/1/runs/65e1945b6a22414cb107ce89a8f58808
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [13]:
def promote_to_stg(version):
    client.set_registered_model_alias(
        name="customer-churn",
        alias="stg",
        version=version
    )


prd_version = None
stg_version = None

try:
    prd_version = client.get_model_version_by_alias("customer-churn", alias="prd")
    prd_run_id = prd_version.run_id
    prd_run = client.get_run(prd_run_id)

    prd_auc = prd_run.data.metrics["roc_auc"]
except Exception as e:
    print(e)

if prd_version is None:
    try:
        stg_version = client.get_model_version_by_alias("customer-churn", alias="stg")
        stg_run_id = stg_version.run_id
        stg_run = client.get_run(stg_run_id)

        stg_auc = stg_run.data.metrics["roc_auc"]
    except Exception as e:
        print(e)


candidate_version = client.get_model_version_by_alias("customer-churn", alias="candidate")
candidate_run_id = candidate_version.run_id
candidate_run = client.get_run(candidate_run_id)

candidate_auc = candidate_run.data.metrics["roc_auc"]

if (stg_version is None and prd_version is None) or (prd_version is None and candidate_auc > stg_auc) or (prd_version is not None and candidate_auc > prd_auc):
    print("Promoting to stage")
    promote_to_stg(version)

INVALID_PARAMETER_VALUE: Registered model alias prd not found.
Promoting to stage